### ISSUE TITLE
Problems about building decoder in loading segmenter

### ISSUE THREAD

**Issue by BenfenYU** [davidbau/dissect#3]
Hi, I'm back again.
when I input "python -m experiment.dissect_experiment", it died.
![image](https://user-images.githubusercontent.com/33017944/96851796-fbf34a80-148a-11eb-804d-a3566c63d79a.png)

Does it mean the decoder is corrupted?

**Comment by davidbau** [comment]
I haven't seen this error message before, but it might mean that the
downloaded segmenter weights file was corrupted.  If you delete the
contents of datasets/segmodel, you can force it to try to download again
fresh.

**Comment by BenfenYU** [comment]
It works, thank you
