### ISSUE TITLE
Unkown Concpt "-"

### ISSUE THREAD

**Issue by AhmadM-DL** [davidbau/dissect#9]
Hello,
While running Dissect I am having the following weird object concept "-".
What does this concept signify?

**Comment by davidbau** [comment]
You should filter it out.  It is an artifact of the multi-label
segmentation process.  Not every pixel needs a label of every category.  If
some pixel is unlabeled, the tensor containing classes will contain a zero
at that location, and zero is translated to the text label "-".

**Comment by AhmadM-DL** [comment]
Okay
